base/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.get_title, name='get_title'),
    url(r'^search/(?P<pk>[0-9]+)/$', views.paper_detail, name='paper_detail'),
    url(r'^journals/$', views.journal_list, name='journal_list'),
    url(r'^keywords/$', views.keyword_list, name='keyword_list'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
 + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papers_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('base.urls'))
]

base/models.py
from django.db import models

class Keyword(models.Model):
    keyword = models.CharField(max_length=128)

    def __str__(self):
        return unicode(self.keyword)

class Journal(models.Model):
    name = models.TextField()
    orig_id = models.IntegerField()

    def __unicode__(self):
        return unicode(self.name)

class Paper(models.Model):
    author = models.TextField()
    date = models.IntegerField(null=True, blank=True)
    title = models.TextField()
    journal = models.ForeignKey(Journal, null=True, blank=True)
    volume = models.CharField(max_length=64, default='')
    page_start = models.CharField(max_length=64, default='')
    page_end = models.CharField(max_length=64, default='')
    keywords = models.ManyToManyField(Keyword)
    reprint = models.BooleanField(default=False)
    lookup = models.CharField(max_length=32, default='')
    pdf = models.FileField(null=True, blank=True)

    def info_string(self):
        info_st = "<i>%s</i> " % self.journal.name
        if self.volume is not "None" and len(self.volume) > 0:
            info_st += "%s, " % self.volume
        if self.page_start is not "None" and len(self.page_start) > 0:
            info_st += "%s " % self.page_start
            if self.page_end is not "None" and len(self.page_end) > 0:
                info_st += "- %s " % self.page_end
        if self.date is not "None" > 0:
            info_st += "(%s)" % self.date
        return info_st

    def keyword_string(self):
        kw_st = (', ').join(['<a href="/?keyword=%s">%s</a>' % (kw.keyword, kw.keyword) for kw in self.keywords.all()])
        return kw_st

    def __unicode__(self):
        return unicode(self.title + ' | ' + self.author)

base/forms.py
from django import forms

class PaperForm(forms.Form):
    title = forms.CharField(required=False)
    author = forms.CharField(required=False)
    journal = forms.CharField(required=False)
    keyword = forms.CharField(required=False)

class DateForm(forms.Form):
    date_start = forms.IntegerField(label='Start', required=False)
    date_end = forms.IntegerField(label='End', required=False)

base/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from models import Paper, Journal, Keyword
from .forms import PaperForm, DateForm

def paper_detail(request, pk):
    paper = get_object_or_404(Paper, pk=pk)
    return render(request, 'base/paper_detail.html', {'paper': paper})

def get_title(request):
    papers = Paper.objects.all()
    # return render(request, 'base/paper_list.html', {'papers': papers})

    # figure out date_start and date_end from database
    dates = [paper.date for paper in papers if isinstance(paper.date, int)]
    date_min = min(dates)
    date_max = max(dates)

    data = request.GET
    paperform = PaperForm(request.GET)

    if 'date_start' not in data:
        dateform = DateForm(initial={'date_start': date_min, 'date_end': date_max})
    else:
        dateform = DateForm(request.GET)

    if 'title' in data and len(data['title']) > 0:
        papers = papers.filter(title__icontains=data['title'])

    if 'author' in data and len(data['author']) > 0:
        papers = papers.filter(author__icontains=data['author'])

    if 'journal' in data and len(data['journal']) > 0:
        papers = papers.filter(journal__name__icontains=data['journal'])

    # start_date and end_date will always be populated
    if 'date_start' in data and len(data['date_start']) > 0:
        papers = papers.filter(Q(date__gte=data['date_start']) | Q(date__isnull=True))
        papers = papers.filter(Q(date__lte=data['date_end'])   | Q(date__isnull=True))

    if 'keyword' in data and len(data['keyword']) > 0:
        papers = papers.filter(keywords__keyword__icontains=data['keyword'])

    return render(request, 'base/search.html', {
        'paperform': paperform,
        'date_min': date_min,
        'date_max': date_max,
        'dateform': dateform,
        'papers': papers})

def journal_list(request):
    journals = Journal.objects.all()
    return render(request, 'base/journal_list.html', {'journals': journals})

def keyword_list(request):
    keywords = Keyword.objects.all()
    return render(request, 'base/keyword_list.html', {'keywords': keywords})

base/templates/base.html
<html>
    <head>
        <title>Mayfly db - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
        <link rel="stylesheet" href="//cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css"/>
        <link rel="stylesheet" href="//cdn.rawgit.com/simeydotme/jQuery-ui-Slider-Pips/master/dist/jquery-ui-slider-pips.css">

        <script src="//code.jquery.com/jquery-2.1.1.js"></script>
        <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
        <script src="//cdn.rawgit.com/simeydotme/jQuery-ui-Slider-Pips/master/dist/jquery-ui-slider-pips.js"></script>
        <script src="//cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
        <script src="//cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
        <style type="text/css">
            input[type="text"] {
                width: 100%;
                padding: 5px;
            }

            input[type="submit"] {
                padding-left: 3em;
                padding-right: 3em;
            }

            #slider .ui-slider-tip {
                visibility: visible;
                opacity: 1;
                top: -30px;
            }
        </style>
    </head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="padding:0" href="{%url 'get_title' %}"><img src="http://i.imgur.com/CubUnUy.png"></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="{%block active_search %}{% endblock %}"><a href="{%url 'get_title' %}">Search</a></li>
              <li class="{%block active_journal %}{% endblock %}"><a href="{%url 'journal_list' %}">Journals</a></li>
              <li class="{%block active_keyword%}{% endblock %}"><a href="{%url 'keyword_list' %}">Kewords</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

base/templates/base/journal_list.html
{% extends "base.html" %}
{% block title %}Journals{% endblock %}
{% block active_journal %}active{% endblock %}
{% block content %}
<div class="container">
    <div>
        <table class="table" id="fancy_table">
            <thead>
                <tr>
                    <th>Journal</th>
                    <th>Number of Papers</th>
                </tr>
            </thead>
            <tbody>
                {% for journal in journals %}
                <tr>
                    <td><a href="/?journal={{ journal.name }}">{{ journal }}</a></td>
                    <td>{{ journal.paper_set.all | length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#fancy_table').DataTable({"bFilter": false, "aaSorting": [[1, 'desc']]});
    } );
</script>
{% endblock %}

base/templates/base/keyword_list.html
{% extends "base.html" %}
{% block title %}Keywords{% endblock %}
{% block active_keyword %}active{% endblock %}
{% block content %}
<div class="container">
    <div>
        <table class="table" id="fancy_table">
            <thead>
                <tr>
                    <th>Keyword</th>
                    <th>Number of Papers</th>
                </tr>
            </thead>
            <tbody>
                {% for keyword in keywords %}
                <tr>
                    <td><a href="/?keyword={{ keyword.keyword }}">{{ keyword }}</a></td>
                    <td>{{ keyword.paper_set.all | length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#fancy_table').DataTable({"bFilter": false, "aaSorting": [[1, 'desc']]});
    } );
</script>
{% endblock %}

base/templates/base/paper_detail.html
{% extends "base.html" %}
{% block title %}Paper Detail{% endblock %}
{% block content %}
<div class="container">
    <h2>{{ paper.title|safe }}</h2>
    <h3>{{ paper.author }}</h3>
    <h4>{{ paper.info_string|safe }}</h4>
    <h4>Keywords: {{ paper.keyword_string|safe }}</h4>
    <h5>
        Reprint:
        {% if paper.reprint %}
        <i class="fa fa-check"></i>
        {% else %}
        <i class="fa fa-times"></i>
        {% endif %}
    <h5>
        {% if paper.pdf %}
        {% if user.is_authenticated or paper.date < 1978 %}
        <iframe src="{{ paper.pdf.url }}" style="width: 100%; height: 100%; max-height: 600px"></iframe>
        {% endif %}
        {% else %}
        Sorry, no PDF available.
        {% endif %}
</div>
{% endblock %}

base/templates/base/search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}
{% block active_search %}active{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="get" id="searchForm">
        <div classs="row">
            <div class="col-md-6"><h4>Title</h4>{{ paperform.title }}</div>
            <div class="col-md-6"><h4>Author</h4>{{ paperform.author }}</div>
            <div class="col-md-6"><h4>Journal</h4>{{ paperform.journal }}</div>
            <div class="col-md-6"><h4>Keywords</h4>{{ paperform.keyword }}</div>
            <div class="col-md-12"><h4>Year</h4><div style="margin:2.4em"id="slider"></div></div>
        </div>
        {{ dateform.date_start.as_hidden }}
        {{ dateform.date_end.as_hidden }}
        <div class="row" style="text-align:center">
            <input type="submit" class="btn btn-primary" value="Search" onclick="DateVals()" />
        </div>
    </form>
    <div>
        <table class="table" id="fancy_table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Journal</th>
                    <th>Year</th>
                    <th>Volume</th>
                    <th>Keywords</th>
                </tr>
            </thead>
            <tbody>
                {% for paper in papers %}
                <tr>
                    <td><a href = "{% url 'paper_detail' pk=paper.pk %}">{{ paper.title|safe }}</a></td>
                    <td>{{ paper.author }}</td>
                    <td>{{ paper.journal }}</td>
                    <td>{{ paper.date }}</td>
                    <td>{{ paper.volume }}</td>
                    <td>{{ paper.keyword_string|safe }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        date_start = $('#id_date_start').val();
        date_end = $('#id_date_end').val();
        $('#fancy_table').DataTable({"bFilter": false});
        $("#slider")
            .slider({
                min: {{ date_min }},
                max: {{ date_max }},
                range: true,
                values: [date_start, date_end]
            })
        .slider("pips", {
        })
            .slider("float");
        $("#slider").on("slidechange", function(e, data){
            date_start = data.values[0];
            date_end = data.values[1];
            $('#id_date_start').attr('value', date_start);
            $('#id_date_end').attr('value', date_end);
        });
    } );
</script>
{% endblock %}